services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    environment:
      TZ: 'Asia/Bangkok'
      PGTZ: 'Asia/Bangkok'
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./app.env
    depends_on:
      - postgres
volumes:
  postgres:
